# Generated by Django 5.2.17 on 2026-09-22 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_alter_bus_options'),
        ('routes', '0003_alter_route_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('departure_at', models.DateTimeField(help_text='UTC.')),
                ('arrival_at', models.DateTimeField(help_text='Estimated, UTC.')),
                ('base_fare_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base_fare_khr', models.DecimalField(decimal_places=0, max_digits=12)),
                ('seats_available', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('departed', 'Departed'), ('completed', 'Completed')], default='scheduled', max_length=15)),
                ('delay_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='routes.route')),
            ],
            options={
                'db_table': 'trips_trip',
                'ordering': ['departure_at'],
            },
        ),
        migrations.CreateModel(
            name='TripSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('booked', 'Booked')], default='available', max_length=10)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('held_by_session_key', models.CharField(blank=True, help_text='Guest hold, when held_by_user is null.', max_length=40)),
                ('held_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_trip_seats', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_seats', to='fleet.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_seats', to='trips.trip')),
            ],
            options={
                'db_table': 'trips_trip_seat',
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'departure_at'], name='trips_trip_route_i_02452b_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='tripseat',
            index=models.Index(fields=['trip', 'status'], name='trips_trip__trip_id_93a6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='tripseat',
            index=models.Index(fields=['status', 'held_until'], name='trips_trip__status_1f50d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripseat',
            constraint=models.UniqueConstraint(fields=('trip', 'seat'), name='unique_trip_seat'),
        ),
    ]
