# Generated by Django 5.2.17 on 2026-09-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_telegram_chat_id'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_trips', to='accounts.operatorstaff'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
