# Generated by Django 5.2.17 on 2026-09-21 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('id_document_number', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_passengers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_saved_passenger',
            },
        ),
        migrations.CreateModel(
            name='OperatorStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('staff_role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('counter_agent', 'Counter agent'), ('conductor', 'Conductor')], max_length=20)),
                ('can_create_bookings', models.BooleanField(default=False)),
                ('can_validate_tickets', models.BooleanField(default=False)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='operators.operator')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_operator_staff',
                'indexes': [models.Index(fields=['operator', 'user'], name='accounts_op_operato_3f72f7_idx')],
            },
        ),
    ]
