# Generated by Django 5.2.17 on 2026-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_savedpassenger_operatorstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Set once the user links Telegram for delivery (Step 9).', max_length=32, null=True),
        ),
    ]
