# Generated by Django 5.2.17 on 2026-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_verified_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='E.164, e.g. +855... (contact only, not used for login)', max_length=16, null=True),
        ),
    ]
