# Generated by Django 5.2.17 on 2026-09-25 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Empty = visible immediately.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Empty = no end.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message_km', models.CharField(max_length=500)),
                ('message_en', models.CharField(max_length=500)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning')], default='info', max_length=10)),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('passengers', 'Passengers'), ('operators', 'Operators')], default='all', max_length=12)),
            ],
            options={
                'db_table': 'content_announcement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Empty = visible immediately.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Empty = no end.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title_km', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('body_km', models.CharField(blank=True, max_length=255)),
                ('body_en', models.CharField(blank=True, max_length=255)),
                ('placement', models.CharField(choices=[('home', 'Home page'), ('search', 'Search results'), ('my_bookings', 'My bookings')], default='home', max_length=15)),
                ('background_color', models.CharField(default='#0D5F6E', help_text='Hex, e.g. #0D5F6E.', max_length=7)),
                ('link_url', models.CharField(blank=True, help_text='Site-relative path or full URL.', max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'content_banner',
                'ordering': ['placement', 'sort_order', '-created_at'],
            },
        ),
    ]
