# Generated by Django 5.2.17 on 2026-09-27 13:53

import apps.content.models
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional. Falls back to background_color when empty.', null=True, upload_to=apps.content.models.banner_image_upload_path, validators=[apps.core.validators.validate_banner_image]),
        ),
    ]
