# Generated by Django 5.2.17 on 2026-09-23 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('operator_approved', 'Operator approved'), ('operator_rejected', 'Operator rejected'), ('booking_cancelled', 'Booking cancelled'), ('refund_issued', 'Refund issued'), ('role_changed', 'Role changed')], max_length=30)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(help_text="The target's public_id, as a string.", max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for a system-triggered action (e.g. a payment webhook cancelling a booking).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_audit_log',
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_audit__action_5c03c3_idx'), models.Index(fields=['target_model', 'target_id'], name='core_audit__target__a02965_idx')],
            },
        ),
    ]
