# Generated by Django 5.2.17 on 2026-09-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('operator_approved', 'Operator approved'), ('operator_rejected', 'Operator rejected'), ('booking_cancelled', 'Booking cancelled'), ('refund_issued', 'Refund issued'), ('role_changed', 'Role changed'), ('trip_status_changed', 'Trip status changed')], max_length=30),
        ),
    ]
