# Generated by Django 5.2.17 on 2026-09-22 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_km', models.CharField(max_length=100)),
                ('country_code', models.CharField(default='KH', help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'routes_city',
                'indexes': [models.Index(fields=['name_en'], name='routes_city_name_en_65dcb1_idx'), models.Index(fields=['name_km'], name='routes_city_name_km_2a918e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_terminating', to='routes.city')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='operators.operator')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_originating', to='routes.city')),
            ],
            options={
                'db_table': 'routes_route',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_km', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='routes.city')),
            ],
            options={
                'db_table': 'routes_stop',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveSmallIntegerField(help_text='1-based order along the route, from origin.')),
                ('offset_minutes', models.PositiveIntegerField(help_text='Minutes from departure at sequence 1.')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='routes.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='routes.stop')),
            ],
            options={
                'db_table': 'routes_route_stop',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['operator'], name='routes_rout_operato_39f8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin_city', 'destination_city'], name='routes_rout_origin__3b9f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['city'], name='routes_stop_city_id_f4391e_idx'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='unique_route_sequence'),
        ),
    ]
