# Generated by Django 5.2.17 on 2026-09-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['name_en']},
        ),
    ]
