# Generated by Django 5.2.17 on 2026-09-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_stop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at']},
        ),
    ]
