# Generated by Django 5.2.17 on 2026-09-25 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='description_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='promocode',
            name='description_km',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='OperatorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Bank transfer reference.', max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='operators.operator')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_operator_payout',
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['operator', 'currency'], name='payments_op_operato_b17557_idx')],
            },
        ),
    ]
