# Generated by Django 5.2.17 on 2026-09-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_promocode_description_en_promocode_description_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('aba_payway', 'ABA PayWay'), ('wing', 'Wing'), ('acleda', 'ACLEDA'), ('counter', 'Pay at counter'), ('mock', 'Mock (dev/test)'), ('demo', 'Demo payment (auto-confirms instantly)')], max_length=15),
        ),
    ]
