# Generated by Django 5.2.17 on 2026-09-21 17:10

import apps.operators.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('name_km', models.CharField(blank=True, max_length=150)),
                ('licence_number', models.CharField(blank=True, max_length=50)),
                ('licence_document', models.FileField(blank=True, null=True, upload_to=apps.operators.models.licence_upload_path)),
                ('contact_phone', models.CharField(max_length=16)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10, help_text='Percent, e.g. 10.00 = 10%', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operators_operator',
            },
        ),
    ]
