# Generated by Django 5.2.17 on 2026-09-25 16:08

import apps.core.validators
import apps.operators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operator_review_checklist_operatorreviewnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='licence_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.operators.models.licence_upload_path, validators=[apps.core.validators.validate_licence_document]),
        ),
    ]
