# Generated by Django 5.2.17 on 2026-09-25 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('contact_phone', models.CharField(max_length=16)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('language', models.CharField(default='km', help_text='Replies are written in this language.', max_length=2)),
                ('category', models.CharField(choices=[('refund_dispute', 'Refund dispute'), ('payment_failed', 'Payment failed'), ('trip_complaint', 'Trip complaint'), ('account', 'Account problem'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting_customer', 'Waiting for customer'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('sla_due_at', models.DateTimeField()),
                ('last_message_at', models.DateTimeField()),
                ('unread_by_staff', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='bookings.booking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_ticket',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], max_length=10)),
                ('channel', models.CharField(choices=[('web', 'Website'), ('sms', 'SMS'), ('telegram', 'Telegram'), ('email', 'Email')], default='web', max_length=10)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'db_table': 'support_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'sla_due_at'], name='support_tic_status_138d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category'], name='support_tic_categor_1ed42d_idx'),
        ),
    ]
