# Generated by Django 5.2.17 on 2026-09-23 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('boarded', 'Boarded'), ('no_show', 'No show')], default='boarded', max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to='bookings.booking')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to='bookings.bookingpassenger')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarding_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boarding_boarding_record',
                'indexes': [models.Index(fields=['booking'], name='boarding_bo_booking_977426_idx')],
                'constraints': [models.UniqueConstraint(fields=('passenger',), name='unique_passenger_boarding_record')],
            },
        ),
    ]
