# Generated by Django 5.2.17 on 2026-09-22 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0003_alter_route_options'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('pnr', models.CharField(db_index=True, max_length=8, unique=True)),
                ('contact_phone', models.CharField(db_index=True, max_length=16)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending_payment', max_length=20)),
                ('booking_channel', models.CharField(choices=[('web', 'Web'), ('counter', 'Counter'), ('telegram', 'Telegram')], default='web', max_length=10)),
                ('currency', models.CharField(choices=[('KHR', 'Khmer Riel'), ('USD', 'US Dollar')], default='USD', max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promo_code', models.CharField(blank=True, max_length=30)),
                ('qr_token', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('refund_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rescheduled_at', models.DateTimeField(blank=True, null=True)),
                ('reschedule_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fare_difference_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('boarding_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='routes.routestop')),
                ('booked_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created_as_staff', to=settings.AUTH_USER_MODEL)),
                ('drop_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='routes.routestop')),
                ('previous_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='trips.trip')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='trips.trip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings_booking',
            },
        ),
        migrations.CreateModel(
            name='BookingPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('id_document_number', models.CharField(blank=True, max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking')),
                ('trip_seat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking_passenger', to='trips.tripseat')),
            ],
            options={
                'db_table': 'bookings_booking_passenger',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pnr', 'contact_phone'], name='bookings_bo_pnr_78b009_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['trip'], name='bookings_bo_trip_id_7b1dd0_idx'),
        ),
    ]
