# Generated by Django 5.2.17 on 2026-09-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('trips', '0002_trip_conductor_trip_driver_name_trip_driver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpassenger',
            name='trip_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_passenger', to='trips.tripseat'),
        ),
    ]
