# Generated by Django 5.2.17 on 2026-09-22 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(choices=[('seated', 'Seated'), ('sleeper', 'Sleeper'), ('mixed', 'Mixed')], default='seated', max_length=10)),
                ('deck_count', models.PositiveSmallIntegerField(default=1)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_layouts', to='operators.operator')),
            ],
            options={
                'db_table': 'fleet_seat_layout',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('seat_number', models.CharField(help_text='e.g. "A1"', max_length=10)),
                ('deck', models.PositiveSmallIntegerField(default=1)),
                ('row_position', models.PositiveSmallIntegerField()),
                ('col_position', models.PositiveSmallIntegerField()),
                ('seat_type', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('is_female_only', models.BooleanField(default=False)),
                ('seat_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='fleet.seatlayout')),
            ],
            options={
                'db_table': 'fleet_seat',
                'ordering': ['deck', 'row_position', 'col_position'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('plate_number', models.CharField(max_length=20)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='e.g. ["ac", "wifi", "usb", "toilet"]')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fleet/buses/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='active', max_length=15)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='operators.operator')),
                ('seat_layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='fleet.seatlayout')),
            ],
            options={
                'db_table': 'fleet_bus',
            },
        ),
        migrations.AddIndex(
            model_name='seatlayout',
            index=models.Index(fields=['operator'], name='fleet_seat__operato_88aa0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('seat_layout', 'seat_number'), name='unique_layout_seat_number'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['operator'], name='fleet_bus_operato_ac29f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.UniqueConstraint(fields=('operator', 'plate_number'), name='unique_operator_plate_number'),
        ),
    ]
