# Generated by Django 5.2.17 on 2026-09-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['plate_number']},
        ),
    ]
