# Generated by Django 5.2.17 on 2026-09-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_bus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='insurance_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='registration_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
