# Generated by Django 5.2.17 on 2026-09-23 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=10)),
                ('recipient', models.CharField(help_text='Phone (E.164), email address, or Telegram chat id.', max_length=255)),
                ('language', models.CharField(choices=[('km', 'Khmer'), ('en', 'English')], default='km', max_length=2)),
                ('template', models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('payment_receipt', 'Payment receipt'), ('departure_reminder', 'Departure reminder'), ('trip_delayed', 'Trip delayed'), ('trip_cancelled', 'Trip cancelled'), ('refund_processed', 'Refund processed')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Template render context.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trips.trip')),
            ],
            options={
                'db_table': 'notifications_notification',
                'indexes': [models.Index(fields=['template', 'booking'], name='notificatio_templat_a45e76_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx')],
            },
        ),
    ]
