# Generated by Django 5.2.17 on 2026-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('payment_receipt', 'Payment receipt'), ('departure_reminder', 'Departure reminder'), ('trip_delayed', 'Trip delayed'), ('trip_cancelled', 'Trip cancelled'), ('refund_processed', 'Refund processed'), ('support_reply', 'Support reply')], max_length=30),
        ),
    ]
